### PR TITLE
Validate onchain send and refund amounts against dust limits

### LINKED ISSUE #683: Validate onchain send amounts and give a clear error response
```
"Service error: service provider error: graphql error: ('Output amount %d sats cannot be smaller than the minimal non dust amount %d sats', 10, 330)"
```

### PR DESCRIPTION
**Pull request by dangeross**
- Validates send amount (fees inclusive/exclusive)
- Validates refund amount after fees
- Removes unused InvalidFees service error

Fixes #683

### CODE REVIEW

File: crates/breez-sdk/core/src/sdk/payments.rs [hunk 1]
```diff
@@ -322,13 +333,24 @@ impl BreezSdk {
...
+
+                // For FeesIncluded, also validate the output after fees
+                if fee_policy == FeePolicy::FeesIncluded {
+                    let output_amount_sats = amount_u64.saturating_sub(fast_fee_sats);
+                    if output_amount_sats < dust_limit_sats {
+                        return Err(SdkError::InvalidInput(format!(
+                            "Amount is below the minimum of {dust_limit_sats} sats required for this address after fees of {fast_fee_sats} sats"
+                        )));
+                    }
+                }
```
Comment (danielgranhao) [inline crates/breez-sdk/core/src/sdk/payments.rs]: Shouldn't this throw an error only if the best case results in an invalid amount?

**Review by roeierez — APPROVED** [review]
