### PR TITLE
Use a consistent db path for default storage

### LINKED ISSUE #369: python: using `default_storage()` causes event loop issues
When using the advanced SDK initialization, calling `default_storage()` results in errors when calling the async functions of the storage because it is no longer in the main event loop. The code:
```python
async def main():  
    try:
        storage = default_storage(data_dir="./.data")
        builder = SdkBuilder(config=config, seed=seed, storage=storage)
        sdk = await builder.build()
        info = await sdk.get_info(request=GetInfoRequest(ensure_synced=True))
        logging.info(f"Balance: {info.balance_sats} sats")
        return sdk
    except Exception as error:
        logging.error(error)
        raise

if __name__ == "__main__":
    asyncio.run(main())
```
causes:
```bash
Exception ignored on calling ctypes callback function <function _UniffiTraitImplStorage.set_cached_item at 0x103a31f80>:
Traceback (most recent call last):
  File "/Users/rosssavage/Source/Projects/breez-sdk-spark-python-test/.venv/lib/python3.13/site-packages/breez_sdk_spark/breez_sdk_spark.py", line 4107, in set_cached_item
    uniffi_out_return[0] = _uniffi_trait_interface_call_async_with_error(make_call, handle_success, handle_error, StorageError, _UniffiConverterTypeStorageError.lower)
  File "/Users/rosssavage/Source/Projects/breez-sdk-spark-python-test/.venv/lib/python3.13/site-packages/breez_sdk_spark/breez_sdk_spark.py", line 10959, in _uniffi_trait_interface_call_async_with_error
    eventloop = _uniffi_get_event_loop()
  File "/Users/rosssavage/Source/Projects/breez-sdk-spark-python-test/.venv/lib/python3.13/site-packages/breez_sdk_spark/breez_sdk_spark.py", line 10892, in _uniffi_get_event_loop
    return asyncio.get_running_loop()
RuntimeError: no running event loop
```

This can be fixed by setting the uniffi event loop, but this needs to be better documented for python (and perhaps we can expose this function more conveniently)
```python
from breez_sdk_spark.breez_sdk_spark import uniffi_set_event_loop

async def main():  
    uniffi_set_event_loop(asyncio.get_event_loop())
```

### LINKED ISSUE #373: sdk: using `default_storage()` directly doesn't isolate the mnemonic/network
With `connect()` the mnemonic fingerprint and network are added to the data dir path, but using `default_storage()` with the SdkBuilder uses the data dir directly without mnemonic fingerprint and network added. This could cause issues in the advanced initialization when switching mnemonics/networks

### PR DESCRIPTION
**Pull request by dangeross**
The used db storage path differs between when using `connect()` and `default_storage()` directly. 

This PR changes the SDK builder to allow either a default storage path or storage implementation to be set. As the `connect()` flow also uses the SDK builder's `with_default_storage()` the used directory is consistent for both flows.

Fixes #373
Closes #369 (`default_storage()` is removed)

### CODE REVIEW

File: crates/breez-sdk/core/src/models/mod.rs [hunk 1]
```diff
@@ -43,6 +44,45 @@ pub struct ConnectRequest {
     pub storage_dir: String,
 }
 
+#[derive(Clone)]
+#[cfg_attr(feature = "uniffi", derive(uniffi::Record))]
+pub struct DefaultStorageRequest {
+    pub storage_dir: String,
+    pub network: Network,
+    pub seed: Seed,
```
Comment (danielgranhao) [inline crates/breez-sdk/core/src/models/mod.rs]: Not that it makes a world of difference, but it feels a bit odd to pass the seed when creating the storage. We could instead provide just the hash suffix. The logic for getting the hash could be moved to a `impl Seed` block. Wdyt?

**Review by danielgranhao — COMMENTED** [review]
Nice! Small comment

File: packages/flutter/rust/src/sdk_builder.rs
Comment (danielgranhao) [inline packages/flutter/rust/src/sdk_builder.rs]: Missing the `with_storage` method here?

Comment (roeierez) [reply packages/flutter/rust/src/sdk_builder.rs]: Right but for now we are ok to omit it from flutter. No regression from previous.
