### PR TITLE
Fix Spark invoice token id validation and add tests

### LINKED ISSUE #387: CLI fails to pay spark token invoice with "Token identifier is required for tokens invoice"
Attempting to pay a spark token invoice fails with `Error: Failed to prepare payment: Invalid input: Token identifier is required for tokens invoice`

Providing the token identifier in the command doesn't help:
```
breez-spark-cli [mainnet]> pay -t btkn1wphzsauyrsudgy6t92zfnd2qlsm762zemarw79g3vu8spy45fnas2nr2yl -r spark1pgss954pr0y8m9nq5gce30plelsvxc5uq3jwxq3qvfdm9mt4punfdc8qzg7qsqgjzqqe5hsgt3dh2g4x4m0fjkeuecp35fs2ypcxu2rhsswr34qnfv4gfxd4gr7r0mfgt805dmc4z9ns7qyjk3x0kyszq05p5szqm2p8pux8mu284jdj3kqpkn895q6fgfd5d2jvk2qz09w23fp3t7h7z0ycv4tdp06ntvcqx8jh34j2wz95hf5hdmdrqg3p67vl7q3syr9n35d
Error: Failed to prepare payment: Invalid input: Token identifier is required for tokens invoice
```

### PR DESCRIPTION
**Pull request by danielgranhao**
Closes #387 

Issue wasn't in the CLI at all. This PR also moves all payment preparation validation logic to a utils module and adds unit tests to prevent such bugs.

### CODE REVIEW

File: crates/breez-sdk/core/src/utils/send_payment_validation.rs [hunk 1]
```diff
@@ -0,0 +1,605 @@
...
+            if requested_token_identifier != token_identifier {
+                return Err(SdkError::InvalidInput(
+                    "Requested token identifier does not match invoice token identifier"
+                        .to_string(),
+                ));
+            }
+        } else {
+            return Err(SdkError::InvalidInput(
+                "Token identifier is required for tokens invoice".to_string(),
+            ));
```
Comment (dangeross) [inline crates/breez-sdk/core/src/utils/send_payment_validation.rs]: I can understand validating if the request token_identifier matches the invoice if set, but is there a reason to force the request token_identifier to be set in this case? It's already in the invoice

**Review by dangeross — APPROVED** [review]
LGTM

**Review by roeierez — APPROVED** [review]
